#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$(find ~/projects ~/.config -mindepth 1 -maxdepth 1 -type d | fzf -q $1 -1)
else
    selected=$(find ~/projects ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

cd "$selected" 
echo "Changed directory to: $selected"
